/** @type {import('tailwindcss').Config} */
// Design tokens dari design system Stitch "After Schola Design System" (Remix):
// primary navy #0B2A5B + royal blue #1D4ED8, heading Plus Jakarta Sans, body Inter.
// Nama utility (font-headline-xl, text-display-lg, space-*, sidebar-width, dst.)
// sengaja mengikuti config Stitch agar markup referensi bisa dipetakan 1:1.
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#ffddb8',
        secondary: '#455e91',
        'tertiary-container': '#825100',
        'surface-tint': '#2151da',
        'on-secondary-fixed': '#001a42',
        'error-container': '#ffdad6',
        'surface-container-high': '#dce9ff',
        'on-surface-variant': '#434655',
        'on-primary': '#ffffff',
        'surface-container-highest': '#d3e4fe',
        error: '#ba1a1a',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#dce1ff',
        outline: '#747686',
        'secondary-fixed-dim': '#aec6ff',
        surface: '#f8f9ff',
        'secondary-fixed': '#d8e2ff',
        'surface-variant': '#d3e4fe',
        'on-tertiary-fixed': '#2a1700',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        tertiary: '#623c00',
        'on-primary-fixed': '#001551',
        'surface-container': '#e5eeff',
        background: '#f8f9ff',
        'secondary-container': '#abc3fe',
        'on-background': '#0b1c30',
        primary: '#0037b0',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#2c4678',
        'surface-dim': '#cbdbf5',
        'surface-container-low': '#eff4ff',
        'primary-container': '#1d4ed8',
        'surface-bright': '#f8f9ff',
        'on-tertiary-container': '#ffcb8f',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#b7c4ff',
        'on-tertiary-fixed-variant': '#653e00',
        'on-secondary-container': '#375082',
        'tertiary-fixed-dim': '#ffb95f',
        'on-error': '#ffffff',
        'on-primary-container': '#cad3ff',
        'outline-variant': '#c4c5d7',
        'on-surface': '#0b1c30',
        'on-primary-fixed-variant': '#0039b5',
        'primary-fixed-dim': '#b7c4ff',
        // Warna brand kunci (dipakai langsung via bg-navy dsb.)
        navy: '#0B2A5B',
        royal: '#1D4ED8',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'topbar-height': '4rem',
        'space-lg': '1.5rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'space-2xs': '0.25rem',
        'space-md': '1rem',
        'gutter-mobile': '1rem',
        'space-xs': '0.5rem',
        'gutter-desktop': '1.5rem',
        'space-sm': '0.75rem',
        'sidebar-width': '16rem',
        'space-xl': '2rem',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-sm': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'label-sm': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'label-md': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'label-lg': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-xl': ['Plus Jakarta Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-xl-mobile': ['Plus Jakarta Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'display-lg-mobile': ['Plus Jakarta Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-xl': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '800' }],
      },
      boxShadow: {
        xs: '0 1px 2px 0 rgb(11 42 91 / 0.04)',
        card: '0 1px 3px 0 rgb(11 42 91 / 0.04), 0 1px 2px -1px rgb(11 42 91 / 0.02)',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.2s ease-out',
      },
    },
  },
  plugins: [],
}
